# Generated by Django 5.0.8 on 2024-08-07 14:11

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
                ('file', models.FileField(null=True, storage=myapp.models.CustomS3Boto3Storage(), upload_to='')),
                ('profile_picture', models.FileField(null=True, storage=myapp.models.CustomS3Boto3Storage(), upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.siteuser')),
            ],
        ),
    ]
