# Generated by Django 5.0.8 on 2024-08-07 14:11

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_siteuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(
                    choices=[('General Mental Health', 'General Mental Health'), ('Academic', 'Academic'),
                             ('Substance Abuse', 'Substance Abuse'), ('Other', 'Other')], max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(
                    choices=[('Not Yet Reviewed', 'Not Yet Reviewed'), ('In Progress', 'In Progress'),
                             ('Resolved', 'Resolved')], default='Not Yet Reviewed', max_length=50)),
                ('comments', models.TextField(blank=True, default='', max_length=1000)),
                (
                'user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.siteuser')),
                ('user_file',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userfile')),
            ],
        ),
    ]
